lsi: false
safe: false
source: ./posts
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
defaults:
- scope:
    path: ""
    type: "posts"
  values:
    layout: post
- scope:
    path: "posts/releases"
  values:
    layout: post
    collection: releases
- scope: # this time for tech shenanigans
    path: "posts/tech"
  values:
    layout: post
    collection: tech
