name: Deploy TypeDoc to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # build the docs
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install TypeDoc
        run: npm install typedoc
      - name: Build
        run: npx typedoc
      - name: List contents of docs
        run: ls docs
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: 'docs'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: docs
